### ISSUE TITLE
API endpoint to get a provider's version number

### ISSUE THREAD

**Issue by jonathankeebler** [compassdigital/compassdigital.provider#19]
....so we can check which version is rolled out

**Comment by coho1988** [comment]
https://teamideaworks.atlassian.net/browse/P2-17

moved to jira

**Comment by jloures** [comment]
@jonathankeebler could you please be a bit more specific about this task?

**Comment by jonathankeebler** [comment]
@jloures I honestly don't remember why we need this. This might predate using CircleCI to do the deploys (which tells us the specific version is deployed).

@coho1988 Do you mind if we just mark this one as invalid?
